---
driver:
  name: vagrant
  vm_hostname: <%= ENV['OS'] %>
  customize:
    memory: <%= ENV['OSR'] %>
    cpus: <%= ENV['OSC'] %>
    name: <%= ENV['OS'] %>
  network:
   - ['private_network', ip: <%= ENV['OSP'] %>]

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['chef_release'] %>
  install_strategy: always
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mynochef
    provisioner:
      download_url: http://10.1.1.30/media/chef-<%= ENV['chef_release'] %>-1.el7.x86_64.rpm

suites:
  - name: objsrv
    run_list:
#      - recipe[objsrv::do_prs]
      - recipe[objsrv::make_nc_os]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
