---
driver:
  name: vagrant
  vm_hostname: <%= ENV['OS'] %>
  customize:
    memory: <%= ENV['OSR'] %>
    cpus: <%= ENV['OSC'] %>
    name: <%= ENV['OS'] %>
  network:
   - ['private_network', ip: <%= ENV['OSP'] %>]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.6

suites:
  - name: objsrv
    run_list:
#      - recipe[objsrv::do_prs]
      - recipe[objsrv::make_nc_os]
    verifier:
      inspec_tests:
        - test/smoke/default
