name 'objsrv'
maintainer 'Ed Overton'
maintainer_email 'bogus@gmail.com'
chef_version '>= 13.0'
license 'Apache-2.0'
description 'Installs/Configures objsrv'
version '1.1.0'
supports 'redhat'
supports 'centos'

issues_url 'https://github.com/emo3/objsrv/issues'
source_url 'https://github.com/emo3/objsrv'

depends 'nc_base'
depends 'nc_tools'
depends 'server_utils'
